# Generated by Django 4.2.7 on 2023-11-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='monIngredient',
            new_name='nomIngredient',
        ),
    ]
