# Generated by Django 4.2.5 on 2023-12-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpizza', '0003_ingredient_image_pizza_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='image',
            new_name='imageIng',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='image',
            new_name='imagePizza',
        ),
    ]
