# Generated by Django 4.2.5 on 2023-12-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpizza', '0004_rename_image_ingredient_imageing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='imageIng',
        ),
    ]
