# Generated by Django 4.2.5 on 2023-12-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpizza', '0005_remove_ingredient_imageing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='imagePizza',
            new_name='image',
        ),
    ]
