# Generated by Django 4.2.5 on 2023-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpizza', '0006_rename_imagepizza_pizza_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='image',
            new_name='imagePizza',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='imageIng',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
